using System.ComponentModel;
using System.IO;
using System.Windows;
using System.Windows.Controls;
using System.Windows.Controls.Primitives;
using System.Windows.Input;
using WpfApp1.Controls;
using WpfApp1.Services;
using WpfApp1.ViewModels;

namespace WpfApp1;

/// <summary>
/// The small bridge between the actual Windows window and the application logic.
/// The matching XAML file describes the controls; its generated code and this
/// "partial" class are compiled together into one MainWindow class.
/// </summary>
/// <remarks>
/// Keep work that requires a real control here: focus, keyboard routing, file drops,
/// and closing the window. Editing and file workflows belong to the view models
/// and services, so those behaviors can also be tested without a visible window.
/// </remarks>
public partial class MainWindow : Window
{
    // readonly means this window keeps the same view-model reference for its lifetime.
    // That view model can still replace the document inside its shared session.
    private readonly MainWindowViewModel _viewModel;

    /// <summary>The constructor WPF uses when App.xaml opens this window.</summary>
    public MainWindow() : this(null) { }

    /// <summary>
    /// Builds the controls and connects their bindings to one shared view model.
    /// Tests may supply a view model with fake dialogs; normal startup supplies null.
    /// </summary>
    public MainWindow(MainWindowViewModel? viewModel)
    {
        // Generated by the XAML compiler: creates the controls and named fields such
        // as DataGrid and InspectorPanel. They do not exist before this call.
        InitializeComponent();
        // WorkArea excludes the taskbar; do not start larger than the usable desktop.
        Width = Math.Min(1540, SystemParameters.WorkArea.Width);
        Height = Math.Min(960, SystemParameters.WorkArea.Height);
        // ?? selects the supplied object when present, otherwise constructs one.
        // DataContext is the starting object for {Binding ...} expressions in XAML.
        _viewModel = viewModel ?? new MainWindowViewModel(new WpfUserInteractionService(this));
        DataContext = _viewModel;
        // Assign the document first: doing so resets the grid's old selection.
        // Then attach the session's selection object, shared with every inspector.
        DataGrid.Document = _viewModel.Session.Document;
        DataGrid.Selection = _viewModel.Session.Selection;
        // += subscribes methods to events (notifications). The session remains the
        // source of truth; these handlers update control wiring or scroll position.
        _viewModel.Session.DocumentReplaced += DocumentReplaced;
        _viewModel.Session.Selection.Changed += SelectionChanged;
        _viewModel.PropertyChanged += ViewModelPropertyChanged;
        _viewModel.GridFocusRequested += GridFocusRequested;
        Closed += Window_Closed;
        // A test's own command-line arguments must never be treated as file paths.
        if (viewModel is null) Loaded += OpenCommandLineFile;
    }

    /// <summary>Opens an optional startup file once the normal application window has loaded.</summary>
    private async void OpenCommandLineFile(object sender, RoutedEventArgs e)
    {
        // Unsubscribe so a later Loaded event cannot reopen the file. The first
        // command-line argument is the executable's name, hence Skip(1).
        Loaded -= OpenCommandLineFile;
        var path = Environment.GetCommandLineArgs().Skip(1).FirstOrDefault();
        // Startup has only the untouched example packet, so there is nothing to
        // ask the user to save. Await waits for completion without blocking the UI.
        if (path is not null && File.Exists(path)) await _viewModel.OpenPathAsync(path, false);
    }

    /// <summary>Points the custom grid at the newly opened document.</summary>
    private void DocumentReplaced(object? sender, EventArgs e) => DataGrid.Document = _viewModel.Session.Document;
    /// <summary>Keeps the active byte visible when any panel changes the shared selection.</summary>
    private void SelectionChanged(object? sender, EventArgs e) => DataGrid.ScrollToByte(_viewModel.Session.Selection.ActiveByteOffset);
    /// <summary>Returns keyboard input to the grid after a command such as Go to offset.</summary>
    private void GridFocusRequested(object? sender, EventArgs e) => DataGrid.Focus();
    /// <summary>A double-click or Enter in the grid moves focus to the existing byte editor.</summary>
    private void Grid_EditRequested(object? sender, ByteEditEventArgs e) => InspectorPanel.FocusByteEditor();
    /// <summary>Reports grid-driven width or row-fitting changes so settings and save state update.</summary>
    private void Grid_LayoutSettingsChanged(object? sender, EventArgs e) => _viewModel?.NotifyGridLayoutChanged();
    /// <summary>Expands or collapses the display settings; this changes only the visible controls.</summary>
    private void DisplayOptions_Click(object sender, RoutedEventArgs e) => InspectorPanel.ToggleDisplayOptions();

    /// <summary>Shows a wait cursor while the session has an outstanding file operation.</summary>
    private void ViewModelPropertyChanged(object? sender, PropertyChangedEventArgs e)
    {
        // A null property name means "all properties may have changed."
        // A null Cursor removes our override and restores WPF's normal cursor behavior.
        if (e.PropertyName is null or nameof(MainWindowViewModel.IsBusy))
            Cursor = _viewModel.IsBusy ? Cursors.Wait : null;
    }

    /// <summary>Opens the button's XAML-defined menu below the button.</summary>
    private void More_Click(object sender, RoutedEventArgs e)
    {
        // This pattern checks the sender's type and extracts a non-null menu at
        // the same time. PlacementTarget also supplies the menu's binding context.
        if (sender is not Button { ContextMenu: { } menu } button) return;
        menu.PlacementTarget = button;
        menu.Placement = PlacementMode.Bottom;
        menu.IsOpen = true;
    }

    /// <summary>
    /// Routes application shortcuts before WPF sends the key to the focused control.
    /// A focused text box keeps its own copy and text-undo behavior.
    /// </summary>
    private void Window_PreviewKeyDown(object sender, KeyEventArgs e)
    {
        bool control = Keyboard.Modifiers.HasFlag(ModifierKeys.Control);
        bool shift = Keyboard.Modifiers.HasFlag(ModifierKeys.Shift);
        bool textFocus = Keyboard.FocusedElement is TextBox;
        bool editingText = Keyboard.FocusedElement is TextBox { IsReadOnly: false };
        // A switch expression chooses a command object, but does not execute it.
        // The "when" conditions avoid stealing ordinary text-editing shortcuts.
        ICommand? command = control ? e.Key switch
        {
            Key.O => _viewModel.OpenCommand,
            Key.S => shift ? _viewModel.SaveProjectCommand : _viewModel.SaveBinaryCommand,
            Key.E => _viewModel.ExportTextCommand,
            Key.G => _viewModel.GoToOffsetCommand,
            Key.Z when !editingText => _viewModel.UndoCommand,
            Key.Y when !editingText => _viewModel.RedoCommand,
            Key.C when !textFocus => _viewModel.CopyCommand,
            _ => null
        } : e.Key == Key.Space && DataGrid.IsKeyboardFocusWithin ? _viewModel.FlipSelectionCommand : null;
        if (command is null) return;
        // Stop the same recognized shortcut reaching another control, even if
        // its application command is disabled (for example while a file is loading).
        e.Handled = true;
        if (command.CanExecute(null)) command.Execute(null);
    }

    /// <summary>Advertises whether Windows may drop files here; other dragged data is rejected.</summary>
    private void Window_DragOver(object sender, DragEventArgs e)
    {
        e.Effects = !_viewModel.IsBusy && e.Data.GetDataPresent(DataFormats.FileDrop) ? DragDropEffects.Copy : DragDropEffects.None;
        e.Handled = true;
    }

    /// <summary>Opens the first dropped file through the same workflow as the Open command.</summary>
    private async void Window_Drop(object sender, DragEventArgs e)
    {
        e.Handled = true;
        if (!_viewModel.IsBusy && e.Data.GetData(DataFormats.FileDrop) is string[] { Length: > 0 } paths)
            await _viewModel.OpenPathAsync(paths[0]);
    }

    /// <summary>Cancels closing if an operation is busy or the user has not resolved unsaved work.</summary>
    private void Window_Closing(object? sender, CancelEventArgs e) => e.Cancel = !_viewModel.ConfirmClose();

    /// <summary>Disconnects event subscriptions and disposes the session after closing succeeds.</summary>
    private void Window_Closed(object? sender, EventArgs e)
    {
        // Event publishers retain references to their listeners. -= removes those
        // references so a closed window cannot keep receiving callbacks or stay alive
        // solely because a longer-lived object still knows its handlers.
        _viewModel.Session.DocumentReplaced -= DocumentReplaced;
        _viewModel.Session.Selection.Changed -= SelectionChanged;
        _viewModel.PropertyChanged -= ViewModelPropertyChanged;
        _viewModel.GridFocusRequested -= GridFocusRequested;
        _viewModel.Dispose();
        // Detach the custom control too; it subscribes directly to document and
        // selection events independently of the window's subscriptions above.
        DataGrid.Document = null;
        DataGrid.Selection = new BitExplorer.Core.BitSelection();
    }
}
